language:
  - python

python:
  - 3.8

install:
  - pip install pytest-cov
  - pip install coverage==5.2.1
  - pip install codecov

script:
  - pytest --cov=./

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false