language:
  - python

python:
  - 3.8

install:
  - pip install pytest-cov

script:
  - pip install coverage==5.2.1
  - pytest

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false