version: "3.4"

# NETWORK #
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16

# VOLUMES #
volumes:
  mysql:
    driver: local
# ----------------------------- #

services:
  # MySQL #
  mysql:
    image: mysql:5.6
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: secret
    networks: 
      default:
        ipv4_address: 172.21.0.200
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

